repos:
- repo: git@github.com:pre-commit/pre-commit-hooks
  rev: v2.3.0
  hooks:
  - id: debug-statements
  - id: trailing-whitespace
  - id: check-merge-conflict
  - id: check-ast
  - id: check-byte-order-marker
  - id: check-json
  - id: check-symlinks
  - id: check-vcs-permalinks
  - id: check-xml
  - id: check-yaml
  - id: forbid-new-submodules
  - id: flake8
    args: ['--exclude=docs/*,*migrations*,_schema.py,_dsig.py', '--ignore=E501,W503']

- repo: local
  hooks:
  - id: check-datetime-now
    name: check_datetime_now
    description: Prefer datetime.utcnow()
    language: pygrep
    entry: 'datetime\.now\(\)'
    types: [python]

- repo: https://github.com/pre-commit/mirrors-isort
  rev: v4.3.21
  hooks:
  - id: isort
    additional_dependencies: ['toml']

- repo: https://github.com/python/black
  rev: 19.3b0
  hooks:
    - id: black
