language: python

cache: pip

matrix:
    include:
        - python: '3.6.0'
        - python: '3.6.1'
        - python: '3.6.2'
        - python: '3.6.3'
        - python: '3.6.4'
        - python: '3.6.5'
        - python: '3.7.0'
          dist: xenial
          sudo: true

install:
  - pip install -r requirements.txt
  - pip install coveralls

script:
  - coverage run --source=PyNFSe setup.py test

after_success:
  - coveralls